library(plyr)
library(utils)

dataCleansing<-function(data){
  
  #remove change direct/indirection proof; remove end; remove rule with #NAME? or login
  data<-data[data$action != 8,]
  data<-data[data$action != 98,]
  data<-data[data$rule != "#NAME?",]
  data<-data[!(data$preState=="" | data$postState=="undefined"),]
  
  #remove hint with content 'undefined' and 'no hint available'
  badHint<-c("undefined", "No hint available for this step.")
  data<-data[!data$hintGiven %in% badHint,]
  
  #remove duplicate hint request on the same state
  data<-data[!(data$rule %in% "get" & duplicated(data[,c("studentID", "rule", "preState", "currPrb","hintGiven")])),]
  
}

#TODO: add in skill name ans throw out rulevariables that are not the skill related
#help seeking behaviors related features
#input: hintStats is file generated by hintTagFeatureEngineering.r (yihuan's) ; data is cleaned raw action log
hsFeatures<-function(hintStats, data){
  #hintStats<-hintStats[hintStats$rule != "",]
  hintStats$skillProficiency<-""
  hintStats$hintCorrectness<-TRUE
  hintStats$hintedRule<-NA
  hintStats$scoreHintedRule<-NA
  hintStats$PLHintedRule<-NA
  hintStats$numCorrectHintedRuleCurr<-NA
  hintStats$numCorrectHintedRuleTotal<-NA
  hintStats$numWrongHintedRuleTotal<-NA
  hintStats$numWrongHintedRuleCurr<-NA
  hintStats$numHintedRuleCurr<-NA
  hintStats$numHintedRuleTotal<-NA
  hintStats$accuracyHintedRuleCurr<-NA
  hintStats$accuracyHintedRuleTotal<-NA
  hintStats$prevActionTime<-NA
  hintStats$prevAction<-NA
  hintStats$prevRuleAppCorrectness<-NA
  hintStats$prevRuleTime<-NA
  hintStats$prevStateChangeTime<-NA
  
  i<-1
  #27, 37 error data
  while (i<=nrow(hintStats)){
    print(i)
    #skill features: poorly known skill, well-known skill, first encounter of a skill
    skill<-toupper(skillInHint(hintStats[i, ], data))
    if (skill != ""){
      hintStats[i,"hintedRule"]<-skill
      hintStats[i,"scoreHintedRule"]<-hintStats[i,paste("score", skill, sep="")]
      hintStats[i,"PLHintedRule"]<-hintStats[i,paste("PL", skill, sep="")]
      hintStats[i,"numCorrectHintedRuleCurr"]<-hintStats[i,paste("numCorrect", skill,"Curr", sep="")]
      hintStats[i,"numCorrectHintedRuleTotal"]<-hintStats[i,paste("numCorrect", skill,"Total", sep="")]
      hintStats[i,"numWrongHintedRuleTotal"]<-hintStats[i,paste("numWrong", skill,"Curr", sep="")]
      hintStats[i,"numWrongHintedRuleCurr"]<-hintStats[i,paste("numWrong", skill,"Total", sep="")]
      hintStats[i,"numHintedRuleCurr"]<-hintStats[i,paste("num", skill,"Curr", sep="")]
      hintStats[i,"numHintedRuleTotal"]<-hintStats[i,paste("num", skill,"Total", sep="")]
      hintStats[i,"accuracyHintedRuleCurr"]<-hintStats[i,"numCorrectHintedRuleCurr"]/hintStats[i,"numHintedRuleCurr"]
      hintStats[i,"accuracyHintedRuleTotal"]<-hintStats[i,"numCorrectHintedRuleTotal"]/hintStats[i,"numHintedRuleTotal"]
    }
    if (skill != ""){
      attrName<-paste("score", skill, sep="")
      KTScore<-as.numeric(strsplit(as.character(hintStats[i, attrName]), ";")[[1]][1])
      if (KTScore == 0){
        hintStats[i,"skillProficiency"]<-"FSK" #first encounter a skill
      }
      else if (KTScore < 0.5){
        hintStats[i,"skillProficiency"]<-"LSK" #first encounter a skill
      }
      else{
        hintStats[i,"skillProficiency"]<-"HSK" #first encounter a skill
      }
    }
    else{
      hintStats[i,"hintCorrectness"]<-FALSE
      print(i)
    }
    
    #time&help seeking behaviors
    problemData<-data[data$currPrb %in% hintStats[i, "currPrb"],]
    rowHint<-which(problemData$studentID %in% hintStats[i,"studentID"] & problemData$hintGiven %in% hintStats[i,"hintGiven"]
                  & problemData$interaction %in% hintStats[i,"interaction"]& problemData$elTime %in% hintStats[i,"elTime"])
    
    j<-rowHint-1
    ####### here is what i am atrea
    while (j>0){
      if (is.na(hintStats[i,"prevAction"])){
        hintStats[i,"prevAction"]<-problemData[j, "action"]
        prevAction<-problemData[j, "action"]
        hintStats[i,"prevActionTime"]<-calculateElTime(problemData,j, rowHint)
        prevActionTime<-hintStats[i,"prevActionTime"]
        if ((prevAction == 3 || prevAction == 5)
            && is.na(hintStats[i,"prevRuleAppCorrectness"]) && is.na(hintStats[i,"prevRuleTime"])){  #first rule application before hint
          hintStats[i,"prevRuleAppCorrectness"]<-(problemData[j, "error"]==0)
          hintStats[i,"prevRuleTime"]<-calculateElTime(problemData, j, rowHint)
        }
      }
      if (!(problemData[j, "preState"] %in% problemData[j, "postState"]) &&
            is.na(hintStats[i, "prevStateChangeTime"])){
        hintStats[i,"prevStateChangeTime"]<-calculateElTime(problemData, j, rowHint)
      }
      j<-j-1
    }
    i<-i+1
  }
  return (hintStats)
}



#find the skill requested by first level hint
#find all rules applied that make the node occur, assume the most common one is the skill
skillInHint<-function(hintRow, data){
  hintedNode<-gsub("Try to derive ", "", hintRow$hintGiven)
  hintedNode<-gsub(" working forward.", "", hintedNode)
  hintedNode<-gsub(" working backward.", "", hintedNode)
  if (nchar(hintedNode)>2){
    hintedNode<-paste("(", hintedNode, ")", sep="")
  }
  hintedNode<-regexEscapeChar(paste(",", hintedNode, "[", sep=""))
  
  problem<-hintRow$currPrb
  probData<-data[data$currPrb %in% problem,]
  ruleAppliedRows<-probData[probData$action == 3 | probData$action == 5,]
  ruleAppliedRows<-ruleAppliedRows[grepl(hintedNode, ruleAppliedRows$postState) & !grepl(hintedNode, ruleAppliedRows$preState),]
  if (nrow(ruleAppliedRows) == 0){
    return ("")
  }
  else{
    skill<-tail(names(sort(table(ruleAppliedRows$rule))), 1)
    return (skill)
  }
}


######### helper: elTime may involve restart or other weird recount behavior #####
calculateElTime<-function(data, beforeRow, afterRow){
  timeCost<-data[afterRow,"elTime"]-data[beforeRow,"elTime"]
  if (timeCost <= 0 ){
    timeCost<-0
    i<-1
    while (i<nrow(data)){
      if (data[i+1, "elTime"] < data[i, "elTime"]){
        timeCost<-timeCost+data[i, "elTime"]
      }
      i<-i+1
    }
    timeCost<-timeCost + data[afterRow,"elTime"]
  }
  return (timeCost)
}

#regex replace
regexEscapeChar<-function(regex){
  regex<-gsub("\\+","\\\\+", regex)
  regex<-gsub("\\-","\\\\-", regex)
  regex<-gsub("\\*","\\\\*", regex)
  regex<-gsub("\\(","\\\\(", regex)
  regex<-gsub("\\)","\\\\)", regex)
  regex<-gsub("\\]","\\\\]", regex)
  regex<-gsub("\\[","\\\\[", regex)
  regex<-gsub("\\>","\\\\>", regex)
  return (regex)
}


#load data
inputFilePath <- "E:\\Courses\\CSC 791 Data Analysis for User Adaptive Systems\\CSC791_Project\\Data\\Cond5\\Cond5_HintFollow.csv"
inputFilePath2 <- "E:\\Courses\\CSC 791 Data Analysis for User Adaptive Systems\\CSC791_Project\\Data\\Cond5\\Cond5_Clean.csv"
data <- read.csv(inputFilePath)
data2 <- read.csv(inputFilePath2)

#clean data
data<-dataCleansing(data)
newdata <- hsFeatures(data,data2)

#write data
outputFilePath <- "E:\\Courses\\CSC 791 Data Analysis for User Adaptive Systems\\CSC791_Project\\Data\\Cond5\\Cond5_AllFeature.csv"
write.csv(newdata,file = outputFilePath)
